[build]
  command = "echo 'No build step required for Node.js API'"  # Não é necessário um comando de build
  publish = "docs"  # Diretório de publicação para a documentação OpenAPI (ajuste conforme necessário)

[[headers]]
  for = "/alunos"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/alunos/{id}"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, PUT, DELETE"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/alunos/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
